import { Profile, Project, Comment, Notification, PlatformStats } from "@/types";

export const MOCK_PROFILES: Profile[] = [
  {
    id: "user-1",
    username: "geray_dev",
    full_name: "Geray Heybetov",
    developer_title: "Full-Stack Developer",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
    bio: "Senior Full-Stack Developer & Software Architect building scalable web applications.",
    location: "Baku, Azerbaijan",
    website: "https://gerayheybetov.dev",
    github_username: "octocat",
    linkedin_url: "https://linkedin.com/in/geray-heybetov",
    role: "admin",
    created_at: "2026-01-15T10:00:00Z",
    skills: ["Next.js", "React", "TypeScript", "Node.js", "PostgreSQL", "Docker", "Tailwind CSS"],
    followers_count: 142,
    following_count: 38,
    projects_count: 6,
    is_following: false,
  },
  {
    id: "user-2",
    username: "aisha_codes",
    full_name: "Aisha Aliyeva",
    developer_title: "Frontend Developer",
    avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&auto=format&fit=crop&q=80",
    bio: "Frontend Engineer & UI/UX enthusiast building scalable web applications.",
    location: "Sumqayit, Azerbaijan",
    website: "https://aishacodes.io",
    github_username: "torvalds",
    linkedin_url: "https://linkedin.com/in/aisha-aliyeva",
    role: "developer",
    created_at: "2026-02-01T12:30:00Z",
    skills: ["React", "Vue.js", "Tailwind CSS", "Framer Motion", "Figma", "JavaScript"],
    followers_count: 89,
    following_count: 45,
    projects_count: 4,
    is_following: true,
  },
  {
    id: "user-3",
    username: "murad_backend",
    full_name: "Murad Hasanov",
    developer_title: "Backend Developer",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80",
    bio: "Backend Lead Specialist. Python & Go enthusiast focusing on microservices and performance.",
    location: "Baku, Azerbaijan",
    website: "https://muradhasanov.com",
    github_username: "gaearon",
    linkedin_url: "https://linkedin.com/in/murad-hasanov",
    role: "developer",
    created_at: "2026-02-10T14:15:00Z",
    skills: ["Python", "Django", "FastAPI", "Go", "PostgreSQL", "Redis", "AWS"],
    followers_count: 215,
    following_count: 60,
    projects_count: 5,
    is_following: false,
  },
  {
    id: "user-4",
    username: "leyla_ai",
    full_name: "Leyla Sultanova",
    developer_title: "AI / Data Engineer",
    avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80",
    bio: "AI Engineer & Data Scientist crafting intelligent agentic systems and LLM workflows.",
    location: "Ganja, Azerbaijan",
    website: "https://leyla-ai.dev",
    github_username: "sindresorhus",
    linkedin_url: "https://linkedin.com/in/leyla-sultanova",
    role: "developer",
    created_at: "2026-02-20T09:00:00Z",
    skills: ["AI", "Python", "PyTorch", "LangChain", "Next.js", "TypeScript"],
    followers_count: 178,
    following_count: 52,
    projects_count: 3,
    is_following: false,
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: "proj-1",
    user_id: "user-1",
    title: "Deloop - Developer Platform",
    description: "Full-stack developer platform integrating GitHub API, project showcases, real-time comments, and developer networking.",
    cover_image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=80",
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Supabase", "Framer Motion"],
    github_url: "https://github.com/octocat/Deloop-platform",
    live_demo_url: "https://Deloop-demo.vercel.app",
    category: "Full Stack",
    status: "Completed",
    views_count: 1420,
    likes_count: 87,
    comments_count: 14,
    created_at: "2026-03-01T10:00:00Z",
    profile: MOCK_PROFILES[0],
    user_has_liked: true,
  },
  {
    id: "proj-2",
    user_id: "user-2",
    title: "UI Artisan - Modern Component Library",
    description: "Accessible, dark-first UI components for React and Tailwind CSS featuring smooth physics-based micro-animations.",
    cover_image: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=800&auto=format&fit=crop&q=80",
    technologies: ["React", "TypeScript", "Tailwind CSS", "Framer Motion"],
    github_url: "https://github.com/torvalds/ui-artisan",
    live_demo_url: "https://ui-artisan.dev",
    category: "Frontend",
    status: "Completed",
    views_count: 980,
    likes_count: 64,
    comments_count: 8,
    created_at: "2026-03-05T14:30:00Z",
    profile: MOCK_PROFILES[1],
    user_has_liked: false,
  },
  {
    id: "proj-3",
    user_id: "user-3",
    title: "FastCache - High-Performance Distributed Key-Value Store",
    description: "Blazing fast in-memory store written in Go with automatic LRU eviction policy and gRPC interface.",
    cover_image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80",
    technologies: ["Go", "gRPC", "Docker", "PostgreSQL", "Redis"],
    github_url: "https://github.com/gaearon/fast-cache",
    live_demo_url: "https://fastcache.io",
    category: "Backend",
    status: "In Progress",
    views_count: 650,
    likes_count: 42,
    comments_count: 5,
    created_at: "2026-03-10T11:00:00Z",
    profile: MOCK_PROFILES[2],
    user_has_liked: false,
  },
  {
    id: "proj-4",
    user_id: "user-4",
    title: "CodeInsight AI - Automated Code Review Assistant",
    description: "AI agent that analyzes pull requests, detects architectural flaws, security issues, and suggests refactoring patches.",
    cover_image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
    technologies: ["Python", "FastAPI", "AI", "TypeScript", "Next.js"],
    github_url: "https://github.com/sindresorhus/code-insight-ai",
    live_demo_url: "https://codeinsight.ai",
    category: "AI",
    status: "Planning",
    views_count: 1120,
    likes_count: 95,
    comments_count: 19,
    created_at: "2026-03-15T16:45:00Z",
    profile: MOCK_PROFILES[3],
    user_has_liked: true,
  },
];

export const MOCK_COMMENTS: Comment[] = [
  {
    id: "comm-1",
    project_id: "proj-1",
    user_id: "user-2",
    content: "Əla layihədir! Kod strukturu və responsive UI dizaynı çox təmiz işlənib.",
    created_at: "2026-03-02T11:20:00Z",
    profile: MOCK_PROFILES[1],
  },
  {
    id: "comm-2",
    project_id: "proj-1",
    user_id: "user-3",
    content: "Supabase Auth və GitHub API inteqrasiyası superdir. Backend daxili hissəsi çox məntiqli qurulub.",
    created_at: "2026-03-03T15:40:00Z",
    profile: MOCK_PROFILES[2],
  },
  {
    id: "comm-3",
    project_id: "proj-4",
    user_id: "user-1",
    content: "AI agentic workflow ideyası çox maraqlıdır. PyTorch modellərini necə optimize etmisiniz?",
    created_at: "2026-03-16T09:12:00Z",
    profile: MOCK_PROFILES[0],
  }
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "notif-1",
    user_id: "user-1",
    actor_id: "user-2",
    type: "follow",
    is_read: false,
    created_at: "2026-03-18T10:15:00Z",
    actor: MOCK_PROFILES[1],
  },
  {
    id: "notif-2",
    user_id: "user-1",
    actor_id: "user-4",
    type: "like",
    project_id: "proj-1",
    is_read: false,
    created_at: "2026-03-17T14:22:00Z",
    actor: MOCK_PROFILES[3],
    project: { id: "proj-1", title: "Deloop - Developer Platform" },
  },
  {
    id: "notif-3",
    user_id: "user-1",
    actor_id: "user-3",
    type: "comment",
    project_id: "proj-1",
    is_read: true,
    created_at: "2026-03-16T18:05:00Z",
    actor: MOCK_PROFILES[2],
    project: { id: "proj-1", title: "Deloop - Developer Platform" },
  }
];

export const MOCK_STATS: PlatformStats = {
  total_users: 48,
  total_projects: 32,
  completed_projects: 24,
  total_comments: 156,
  total_likes: 420,
  new_users_this_month: 12,
};

export const MOCK_MESSAGES = [
  {
    id: "msg-1",
    sender_id: "user-2",
    receiver_id: "user-1",
    content: "Salam Geray! Deloop layihəsinin dizaynı əla alınıb. Next.js 15 istifadə etmisiniz?",
    is_read: true,
    created_at: "2026-03-18T11:00:00Z",
    sender: MOCK_PROFILES[1],
  },
  {
    id: "msg-2",
    sender_id: "user-1",
    receiver_id: "user-2",
    content: "Salam Aisha, çox sağ ol! Bəli, Next.js 15 və Supabase ilə işləyir.",
    is_read: true,
    created_at: "2026-03-18T11:05:00Z",
    sender: MOCK_PROFILES[0],
  },
  {
    id: "msg-3",
    sender_id: "user-3",
    receiver_id: "user-1",
    content: "Xoş gördük! Backend tərəfdə FastAPI inteqrasiyası lazım gəlsə xəbər et.",
    is_read: false,
    created_at: "2026-03-18T14:20:00Z",
    sender: MOCK_PROFILES[2],
  }
];
